# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: BuildPush
    displayName: Build and push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: 'Domas Docker Hub'
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/DevOpsDemo/Dockerfile'
        repository: 'domas911/devopsdemo'
        containerRegistry: 'Domas Docker Hub'
        tags: |
          $(tag)
        arguments: '--build-arg AzureDbConnection=$(AzureDBConnection)'
    - task: Docker@2
      displayName: Push the image
      inputs:
        command: push
        repository: 'domas911/devopsdemo'
        containerRegistry: 'Domas Docker Hub'
        tags: |
          $(tag)
  